version: "3"

services:
  amazon-sales-db:
    image: shandytp/amazon-sales-data-docker-db:latest
    container_name: amazon-sales-db
    environment:
      POSTGRES_DB: etl_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - db_amazon_sales:/var/lib/postgresql/data
    networks:
      - pacmann_net

  data-warehouse:
    image: postgres:latest
    container_name: data-warehouse
    environment:
      POSTGRES_DB: data_warehouse
      POSTGRES_USER: pacmann_dw
      POSTGRES_PASSWORD: pacmann_dw
    ports:
      - "5433:5432"
    volumes:
      - db_data_warehouse:/var/lib/postgresql/data
    networks:
      - pacmann_net

volumes:
  db_amazon_sales:
    name: amazon-sales-db
    external: false

  db_data_warehouse:
    name: data-warehouse
    external: false

networks:
  pacmann_net:
    name: pacmann-net
    driver: bridge
    external: false
